//@version=6
indicator("5Y EPS history", overlay=false)

eps = request.financial(syminfo.tickerid, "EARNINGS_PER_SHARE_DILUTED", "FY")

// detect new financial report
new_report = not na(eps) and eps != eps[1]
// store last 5 values
var float eps0 = na
var float eps1 = na
var float eps2 = na
var float eps3 = na
var float eps4 = na

if new_report
    eps4 := eps3
    eps3 := eps2
    eps2 := eps1
    eps1 := eps0
    eps0 := eps

// ---- table
var table t = table.new(position.top_right, 2, 6)

if barstate.islast
    table.cell(t,0,0,"Year", text_color = color.blue)
    table.cell(t,1,0,"EPS", text_color = color.blue)

    table.cell(t,0,1,"Current", text_color = color.blue)
    table.cell(t,1,1,str.tostring(eps0), text_color = color.blue)

    table.cell(t,0,2,"-1", text_color = color.blue)
    table.cell(t,1,2,str.tostring(eps1), text_color = color.blue)

    table.cell(t,0,3,"-2", text_color = color.blue)
    table.cell(t,1,3,str.tostring(eps2), text_color = color.blue)

    table.cell(t,0,4,"-3", text_color = color.blue)
    table.cell(t,1,4,str.tostring(eps3), text_color = color.blue)

    table.cell(t,0,5,"-4", text_color = color.blue)
    table.cell(t,1,5,str.tostring(eps4), text_color = color.blue)