// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © IT_Wala

//@version=5
indicator("Table", overlay = true)

var myTable = table.new(position = position.bottom_center, columns = 4, rows = 2, bgcolor = color.white, border_width = 1, frame_color = color.green, frame_width = 3, border_color = color.green)

table.cell(table_id = myTable, column = 0, row = 0, text = "Open", text_color = color.white, bgcolor = color.orange)
table.cell(table_id = myTable, column = 1, row = 0, text = "High", text_color = color.white, bgcolor = color.green)
table.cell(table_id = myTable, column = 2, row = 0, text = "Low", text_color = color.white, bgcolor = color.red)
table.cell(table_id = myTable, column = 3, row = 0, text = "Close", text_color = color.white, bgcolor = color.blue)

table.cell(table_id = myTable, column = 0, row = 1, text = str.tostring(open))
table.cell(table_id = myTable, column = 1, row = 1, text = str.tostring(high))
table.cell(table_id = myTable, column = 2, row = 1, text = str.tostring(low))
table.cell(table_id = myTable, column = 3, row = 1, text = str.tostring(close))

//