//@version=6
indicator("Financial Data", overlay = true, format = format.volume, precision = 2)

// Constants
MILLION = 1000000

MAX_NUMBER_OF_HISTORICAL_REPORTS = 10
NOT_AVAILABLE_STRING = "N/A"
MIN_NUMBER_OF_HISTORICAL_REPORTS_FOR_AVERAGING = 5
TTM_VS_AVERAGE_LIMIT = 0.2  // Flag if TTM is over that 20% of average

COLOR_BACKGROUND = color.black
COLOR_FRAME = COLOR_BACKGROUND
COLOR_BORDER = COLOR_BACKGROUND
COLOR_TEXT = color.white
TABLE_BORDER_WIDTH = 1
TABLE_FRAME_WIDTH = 1
TABLE_KEY_TEXT_ALIGN = text.align_right
TABLE_VALUE_TEXT_ALIGN = text.align_center
TABLE_TITLE_TEXT_ALIGN = text.align_center
TABLE_TEXT_SIZE = size.normal

COLOR_ALERT = color.red
COLOR_WARNING = color.orange
COLOR_GOOD = color.green
COLOR_NEUTRAL = COLOR_BACKGROUND

FLOAT_ALERT = 50
FLOAT_GOOD = 100

EPS_ALERT = 0

PB_ALERT = 3.5
PB_GOOD = 1.5
PB_ALERT_LEVEL2 = 0

DE_ALERT = 2
DE_GOOD = 1

PEG_GOOD = 1
PEG_ALERT = 0

DIVIDEND_GOOD = 0

GROSS_MARGIN_ALERT = 0
GROSS_MARGIN_GOOD = 30

NET_MARGIN_ALERT = 0
NET_MARGIN_GOOD = 5

CASH_FLOW_GOOD = 0

EBIT_GOOD = 0

EBITDA_GOOD = 0

ROE_ALERT = 0
ROE_GOOD = 15

ROA_ALERT = 3
ROA_GOOD = 5

ROIC_ALERT = 8
ROIC_GOOD = 15

// Function that around to 2 decimals
truncate(num) =>
    factor = math.pow(10, 2)
    int(num * factor) / factor

// -----EPS and PE historical data-----
// --- pull EPS
eps_current = request.financial(syminfo.tickerid, "EARNINGS_PER_SHARE_DILUTED", "TTM")
eps_historic = request.financial(syminfo.tickerid, "EARNINGS_PER_SHARE_DILUTED", "FY")

// --- detect new annual report
new_report = not na(eps_historic) and eps_historic != eps_historic[1]

getEpsHistoric(occurence) =>
    ta.valuewhen(new_report, eps_historic, occurence)

getEpsHistoricString(occurence) =>
    eps_ = getEpsHistoric(occurence)
    if not na(eps_) and eps_ != 0
        str.tostring(truncate(eps_))
    else
        NOT_AVAILABLE_STRING

getPeHistoric(occurence) =>
    eps_ = getEpsHistoric(occurence)
    if not na(eps_) and eps_ != 0
        ta.valuewhen(new_report, close, occurence) / eps_
    else
        na

getPeHistoricString(occurence) =>
    pe_ = getPeHistoric(occurence)
    if not na(pe_)
        str.tostring(truncate(pe_))
    else
        NOT_AVAILABLE_STRING

getYearHistoricString(occurence) =>
    year_ = ta.valuewhen(new_report, year, occurence)
    if not na(year_)
        str.tostring(year_)
    else
        NOT_AVAILABLE_STRING

// precompute year/EPS strings once per calc for consistent rendering.
max_years = 0
year_strings = array.new_string()
eps_strings = array.new_string()
pe_strings = array.new_string()
eps_values = array.new_float()
pe_values = array.new_float()

f_get_from_occurence(occurence) =>
    [getYearHistoricString(occurence), getEpsHistoric(occurence), getEpsHistoricString(occurence), getPeHistoric(occurence), getPeHistoricString(occurence)]

f_getHistoricRow(occurrence) =>
    [yr_string, eps_value, eps_string, pe_value, pe_string] = f_get_from_occurence(occurrence)
    valid = not na(eps_value) and eps_value != 0
    [valid, yr_string, eps_value, eps_string, pe_value, pe_string]

addHistoricRow(occurrence) =>
    [valid, yr_string, eps_value, eps_string, pe_value, pe_string] = f_getHistoricRow(occurrence)
    if valid
        array.push(year_strings, yr_string)
        array.push(eps_strings, eps_string)
        array.push(pe_strings, pe_string)
        array.push(eps_values, eps_value)
        array.push(pe_values, pe_value)
    valid

if MAX_NUMBER_OF_HISTORICAL_REPORTS > 0
    if addHistoricRow(0)
        max_years := max_years + 1
if MAX_NUMBER_OF_HISTORICAL_REPORTS > 1
    if addHistoricRow(1)
        max_years := max_years + 1
if MAX_NUMBER_OF_HISTORICAL_REPORTS > 2
    if addHistoricRow(2)
        max_years := max_years + 1
if MAX_NUMBER_OF_HISTORICAL_REPORTS > 3
    if addHistoricRow(3)
        max_years := max_years + 1
if MAX_NUMBER_OF_HISTORICAL_REPORTS > 4
    if addHistoricRow(4)
        max_years := max_years + 1
if MAX_NUMBER_OF_HISTORICAL_REPORTS > 5
    if addHistoricRow(5)
        max_years := max_years + 1
if MAX_NUMBER_OF_HISTORICAL_REPORTS > 6
    if addHistoricRow(6)
        max_years := max_years + 1
if MAX_NUMBER_OF_HISTORICAL_REPORTS > 7
    if addHistoricRow(7)
        max_years := max_years + 1
if MAX_NUMBER_OF_HISTORICAL_REPORTS > 8
    if addHistoricRow(8)
        max_years := max_years + 1
if MAX_NUMBER_OF_HISTORICAL_REPORTS > 9
    if addHistoricRow(9)
        max_years := max_years + 1
if MAX_NUMBER_OF_HISTORICAL_REPORTS > 10
    if addHistoricRow(10)
        max_years := max_years + 1

getPeAverage() =>
    size = array.size(pe_values)
    sum = 0.0
    count = 0
    min_val = 1e20
    max_val = -1e20
    if(size == 0)
        na
    else
        for i = 0 to size - 1
            pe_ = array.get(pe_values, i)
            if not na(pe_)
                sum += pe_
                count += 1
                min_val := math.min(min_val, pe_)
                max_val := math.max(max_val, pe_)
        if count == 0
            na
        else if count >= MIN_NUMBER_OF_HISTORICAL_REPORTS_FOR_AVERAGING
            filtered_sum = sum - min_val - max_val
            filtered_count = count - 2
            filtered_sum / filtered_count
        else
            sum / count

getPeCurrent() =>
    if not na(eps_current) and eps_current != 0
        close / eps_current
    else
        na

getPeTtmColor() =>
    color color = COLOR_NEUTRAL
    pe_average = getPeAverage()
    pe_current = getPeCurrent()

    if not na(pe_current)
        if pe_current <= 0
            color := COLOR_ALERT
        else if not na(pe_average) 
            limit = (pe_average * TTM_VS_AVERAGE_LIMIT) + pe_average
            if pe_current <= pe_average
                color := COLOR_GOOD
            else if pe_current <= limit
                color :=  COLOR_WARNING
            else
                color := COLOR_ALERT
    color
// -----END OF EPS and PE historical data-----

// -----Financial data-----

// Simulate map for all financial data table
stringNamesArray = array.new<string>()
stringValuesArray = array.new<string>()
colorArray = array.new<color>()

// Functions to add key values to map
f_add(name, value, valueColor) =>
    array.push(stringValuesArray, value)
    array.push(stringNamesArray, name)
    array.push(colorArray, valueColor)

// Functions to get values from map by id
f_get_financial(id) =>
    [array.get(stringNamesArray, id), array.get(stringValuesArray, id), array.get(colorArray, id)]

// SECTOR
string sector = syminfo.sector
string subSector = syminfo.industry

// FLOAT
floatShares = request.financial(syminfo.tickerid, "FLOAT_SHARES_OUTSTANDING", "FY") / MILLION
getFloatColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value < FLOAT_ALERT)
            color := COLOR_ALERT
        else if(value >= FLOAT_GOOD)
            color := COLOR_GOOD
        else
            color := COLOR_WARNING
    color
stringName_floatShares = "FLOAT"
stringValue_floatShares = str.tostring(truncate(floatShares)) + "M"

// EARNING PER SHARE and PRICE EARNING RATIO values are kept with second table data
getEpsColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value <= EPS_ALERT)
            color := COLOR_ALERT
        else
            color := COLOR_GOOD
    color
stringName_EPS = "EPS"
stringValue_EPS = "$"+str.tostring(truncate(eps_current))

stringName_PE = "P/E ratio"
stringValue_PE = str.tostring(truncate(getPeCurrent()))

// BOOK VALUE PER SHARE
// Book value per share (BVPS) is the ratio of equity available to common shareholders divided by the number of outstanding shares. 
BVPS  = request.financial(syminfo.tickerid, "BOOK_VALUE_PER_SHARE", "FY")
// PRICE BOOK RATIO
// Price Book Ratio is calculated by dividing the price per share by the book value per share.
PriceBookRatio = close / BVPS
getPriceBookRatioColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value > PB_ALERT)
            color := COLOR_ALERT
        else if(value < PB_ALERT_LEVEL2)
            color := COLOR_ALERT
        else if(value < PB_GOOD)
            color := COLOR_GOOD
        else
            color := COLOR_WARNING
    color
stringName_PB = "P/B ratio"
stringValue_PB = str.tostring(truncate(PriceBookRatio))

// DEBT TO EQUITY RATIO
// Debt to equity ratio is the ratio of Total debt to Total equity
DE = request.financial(syminfo.tickerid, "DEBT_TO_EQUITY", "FY")
getDeRatioColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value >= DE_ALERT)
            color := COLOR_ALERT
        else if(value < DE_GOOD)
            color := COLOR_GOOD
        else
            color := COLOR_WARNING
    color
stringName_DE = "D/E ratio"
stringValue_DE = str.tostring(truncate(DE))

// EPS diluted one year growth
EPS_diluted_one_year_growth = request.financial(syminfo.tickerid, "EARNINGS_PER_SHARE_BASIC_ONE_YEAR_GROWTH", "FQ")

// PRICE EARNING TO GROWTH RATIO
// It is the P/E ratio (price-to-earnings ratio) divided by the growth rate.
PEG = getPeCurrent() / EPS_diluted_one_year_growth
getPegRatioColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value < PEG_ALERT)
            color := COLOR_ALERT
        else if(value <= PEG_GOOD)
            color := COLOR_GOOD
        else
            color := COLOR_ALERT
    color
stringName_PEG = "PEG ratio"
stringValue_PEG = str.tostring(truncate(PEG))

// DIVIDEND
dividend = request.financial(syminfo.tickerid, "DIVIDENDS_YIELD", "FY")
getDividendColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value <= DIVIDEND_GOOD)
            color := COLOR_NEUTRAL
        else
            color := COLOR_GOOD
    color
stringName_dividend = "DIVIDEND"
stringValue_dividend = str.tostring(truncate(dividend)) + "%"

// GROSS MARGIN
grossMargin = request.financial(syminfo.tickerid, "GROSS_MARGIN", "TTM")
getGrossMarginColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value < GROSS_MARGIN_ALERT)
            color := COLOR_ALERT
        else if(value >= GROSS_MARGIN_GOOD)
            color := COLOR_GOOD
        else
            color := COLOR_WARNING
    color
stringName_grossMargin = "GR. MARGIN"
stringValue_grossMargin = str.tostring(truncate(grossMargin)) + "%"

// NET MARGIN
netMargin = request.financial(syminfo.tickerid, "NET_MARGIN", "TTM")
getNetMarginColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value < NET_MARGIN_ALERT)
            color := COLOR_ALERT
        else if(value >= NET_MARGIN_GOOD)
            color := COLOR_GOOD
        else
            color := COLOR_WARNING
    color
stringName_netMargin = "NET MARGIN"
stringValue_netMargin = str.tostring(truncate(netMargin)) + "%"

// CASH FROM OPERATING_ACTIVITIES
cashFlow = request.financial(syminfo.tickerid, "FREE_CASH_FLOW", "TTM") / MILLION
getCashFlowColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value < CASH_FLOW_GOOD)
            color := COLOR_ALERT
        else
            color := COLOR_GOOD
    color
    
stringName_cashFlow = "CASH FLOW"
stringValue_cashFlow = str.tostring(truncate(cashFlow)) + "M"

// EBIT
EBIT = request.financial(syminfo.tickerid, "EBIT", "TTM") / MILLION
getEbitColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value < CASH_FLOW_GOOD)
            color := COLOR_ALERT
        else
            color := COLOR_GOOD
    color
stringName_EBIT = "EBIT"
stringValue_EBIT = str.tostring(truncate(EBIT)) + "M"

// EBITDA
EBITDA = request.financial(syminfo.tickerid, "EBITDA", "TTM") / MILLION
getEbitdaColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value < CASH_FLOW_GOOD)
            color := COLOR_ALERT
        else
            color := COLOR_GOOD
    color
stringName_EBITDA = "EBITDA"
stringValue_EBITDA = str.tostring(truncate(EBITDA)) + "M"

// RETURN ON ASSETS RATIO
ROA = request.financial(syminfo.tickerid, "RETURN_ON_ASSETS", "FY")
getRoaColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value < ROA_ALERT)
            color := COLOR_ALERT
        else if(value >= ROA_GOOD)
            color := COLOR_GOOD
        else
            color := COLOR_WARNING
    color
stringName_ROA = "ROA"
stringValue_ROA = str.tostring(truncate(ROA)) + "%"

// RETURN ON EQUITY RATIO
ROE = request.financial(syminfo.tickerid, "RETURN_ON_EQUITY", "FY")
getRoeColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value < ROE_ALERT)
            color := COLOR_ALERT
        else if(value >= ROE_GOOD)
            color := COLOR_GOOD
        else
            color := COLOR_WARNING
    color
stringName_ROE = "ROE"
stringValue_ROE = str.tostring(truncate(ROE)) + "%"

// RETURN ON INVESTED CAPITAL RATIO
ROIC = request.financial(syminfo.tickerid, "RETURN_ON_INVESTED_CAPITAL", "FY")
getRoicColor(value) =>
    color color = COLOR_NEUTRAL
    if not na(value)
        if(value < ROIC_ALERT)
            color := COLOR_ALERT
        else if(value >= ROIC_GOOD)
            color := COLOR_GOOD
        else
            color := COLOR_WARNING
    color
stringName_ROIC = "ROIC"
stringValue_ROIC = str.tostring(truncate(ROIC)) + "%"

// Stuff all values into map
f_add(stringName_floatShares, stringValue_floatShares, getFloatColor(floatShares))
f_add(stringName_PE, stringValue_PE, getPeTtmColor())
f_add(stringName_EPS, stringValue_EPS, getEpsColor(eps_current))
f_add(stringName_PB, stringValue_PB, getPriceBookRatioColor(PriceBookRatio))
f_add(stringName_DE, stringValue_DE, getDeRatioColor(DE))
f_add(stringName_PEG, stringValue_PEG, getPegRatioColor(PEG))
f_add(stringName_dividend, stringValue_dividend, getDividendColor(dividend))
f_add(stringName_grossMargin, stringValue_grossMargin, getGrossMarginColor(grossMargin))
f_add(stringName_netMargin, stringValue_netMargin, getNetMarginColor(netMargin))
f_add(stringName_cashFlow, stringValue_cashFlow, getCashFlowColor(cashFlow))
f_add(stringName_EBIT, stringValue_EBIT, getEbitColor(EBIT))
f_add(stringName_EBITDA, stringValue_EBITDA, getEbitdaColor(EBITDA))
f_add(stringName_ROA, stringValue_ROA, getRoaColor(ROA))
f_add(stringName_ROE, stringValue_ROE, getRoeColor(ROE))
f_add(stringName_ROIC, stringValue_ROIC, getRoicColor(ROIC))

NUMBER_OF_IDS  = 15
NUMBER_OF_TABLE_TITLES = 2
TOTAL_NUMBER_OF_ROWS = NUMBER_OF_TABLE_TITLES + NUMBER_OF_IDS
TOTAL_NUMBER_OF_COLUMNS = 5

FINANCIAL_ID_COLUMN_INDEX = 0
FINANCIAL_VALUE_COLUMN_INDEX = 1
FINANCIAL_DATA_NUMBER_OF_COLUMNS = 2
EPS_TABLE_ID_COLUMN_INDEX = 2
EPS_TABLE_VALUE_COLUMN_INDEX = 3
PE_TABLE_VALUE_COLUMN_INDEX = 4

LAST_COLUMN_INDEX = TOTAL_NUMBER_OF_COLUMNS - 1

// Display table
var myTable = table.new(position = position.bottom_right, columns = TOTAL_NUMBER_OF_COLUMNS, rows = TOTAL_NUMBER_OF_ROWS, bgcolor = COLOR_BACKGROUND, border_width = TABLE_BORDER_WIDTH, frame_color = COLOR_FRAME, frame_width = TABLE_FRAME_WIDTH, border_color = COLOR_BORDER)
if(barstate.islast)
    table.set_bgcolor(myTable, COLOR_BACKGROUND)
    table.set_frame_color(myTable, COLOR_FRAME)
    table.set_border_color(myTable, COLOR_BORDER)

    titleRowIndex = 0
    table.cell(table_id = myTable, column = 0, row = titleRowIndex, text = sector, text_color = COLOR_TEXT, bgcolor = COLOR_BACKGROUND, text_halign = TABLE_TITLE_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)
    table.merge_cells(table_id = myTable, start_column = 0, start_row = titleRowIndex, end_column = LAST_COLUMN_INDEX, end_row = titleRowIndex)
    titleRowIndex := titleRowIndex + 1
    table.cell(table_id = myTable, column = 0, row = titleRowIndex, text = subSector, text_color = COLOR_TEXT, bgcolor = COLOR_BACKGROUND, text_halign = TABLE_TITLE_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)
    table.merge_cells(table_id = myTable, start_column = 0, start_row = titleRowIndex, end_column = LAST_COLUMN_INDEX, end_row = titleRowIndex)

    for columnIndex = FINANCIAL_ID_COLUMN_INDEX to FINANCIAL_DATA_NUMBER_OF_COLUMNS - 1        
        for rowIndex = titleRowIndex + 1 to NUMBER_OF_IDS + 1
            [name, value, colorValue] = f_get_financial(rowIndex - NUMBER_OF_TABLE_TITLES)
            if(columnIndex == FINANCIAL_ID_COLUMN_INDEX)
                table.cell(table_id = myTable, column = FINANCIAL_ID_COLUMN_INDEX, row = rowIndex, text = name, text_color = COLOR_TEXT, bgcolor = COLOR_BACKGROUND, text_halign = TABLE_KEY_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)
            else
                table.cell(table_id = myTable, column = FINANCIAL_VALUE_COLUMN_INDEX, row = rowIndex, text = value, text_color = COLOR_TEXT, bgcolor = colorValue, text_halign = TABLE_VALUE_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)

    rowIndex = 2

    // Header labels
    table.cell(table_id = myTable, column = EPS_TABLE_VALUE_COLUMN_INDEX, row = rowIndex, text = "EPS", text_color = COLOR_TEXT, bgcolor = COLOR_BACKGROUND, text_halign = TABLE_TITLE_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)
    table.cell(table_id = myTable, column = PE_TABLE_VALUE_COLUMN_INDEX, row = rowIndex, text = "P/E", text_color = COLOR_TEXT, bgcolor = COLOR_BACKGROUND, text_halign = TABLE_TITLE_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)

    // Current TTM values
    rowIndex += 1
    table.cell(table_id = myTable, column = EPS_TABLE_ID_COLUMN_INDEX, row = rowIndex, text = "TTM", text_color = COLOR_TEXT, bgcolor = COLOR_BACKGROUND, text_halign = TABLE_KEY_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)
    eps_text = not na(eps_current) ? str.tostring(truncate(eps_current)) : "N/A"
    table.cell(table_id = myTable, column = EPS_TABLE_VALUE_COLUMN_INDEX, row = rowIndex, text = eps_text, text_color = COLOR_TEXT, bgcolor = getEpsColor(eps_current), text_halign = TABLE_VALUE_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)
    pe_current = getPeCurrent()
    pe_current_text = not na(pe_current) ? str.tostring(truncate(pe_current)) : "N/A"
    table.cell(table_id = myTable, column = PE_TABLE_VALUE_COLUMN_INDEX, row = rowIndex, text = pe_current_text, text_color = COLOR_TEXT, bgcolor = getPeTtmColor(), text_halign = TABLE_VALUE_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)

    // Historical values
    rowIndex += 1
    if max_years == 0
        table.cell(table_id = myTable, column = EPS_TABLE_ID_COLUMN_INDEX, row = rowIndex, text = "No historical EPS", text_color = COLOR_TEXT, bgcolor = COLOR_BACKGROUND, text_halign = text.align_center, text_size = TABLE_TEXT_SIZE)
        table.merge_cells(table_id = myTable, start_column = EPS_TABLE_ID_COLUMN_INDEX, start_row = rowIndex, end_column = LAST_COLUMN_INDEX, end_row = rowIndex)
    else
        occurrence = 0
        for i = rowIndex to max_years + rowIndex - 1
            year_string = array.get(year_strings, occurrence)
            eps_string = array.get(eps_strings, occurrence)
            pe_string = array.get(pe_strings, occurrence)
            table.cell(table_id = myTable, column = EPS_TABLE_ID_COLUMN_INDEX, row = i, text = year_string, text_color = COLOR_TEXT, bgcolor = COLOR_BACKGROUND, text_halign = TABLE_KEY_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)
            table.cell(table_id = myTable, column = EPS_TABLE_VALUE_COLUMN_INDEX, row = i, text = eps_string, text_color = COLOR_TEXT, bgcolor = COLOR_BACKGROUND, text_halign = TABLE_VALUE_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)
            table.cell(table_id = myTable, column = PE_TABLE_VALUE_COLUMN_INDEX, row = i, text = pe_string, text_color = COLOR_TEXT, bgcolor = COLOR_BACKGROUND, text_halign = TABLE_VALUE_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)
            occurrence += 1

        // Average values
        rowIndex += max_years
        table.cell(table_id = myTable, column = EPS_TABLE_ID_COLUMN_INDEX, row = rowIndex, text = "Average", text_color = COLOR_TEXT, bgcolor = COLOR_BACKGROUND, text_halign = TABLE_KEY_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)
        table.merge_cells(table_id = myTable, start_column = EPS_TABLE_ID_COLUMN_INDEX, start_row = rowIndex, end_column = EPS_TABLE_VALUE_COLUMN_INDEX, end_row = rowIndex)
        pe_average = getPeAverage()
        table.cell(table_id = myTable, column = PE_TABLE_VALUE_COLUMN_INDEX, row = rowIndex, text = not na(pe_average) ? str.tostring(truncate(pe_average)) : "N/A", text_color = COLOR_TEXT, bgcolor = COLOR_BACKGROUND, text_halign = TABLE_VALUE_TEXT_ALIGN, text_size = TABLE_TEXT_SIZE)