//@version=5
strategy("Long Swing strategy (Weekly)", overlay=true)

// +++ Modify to buy:
// - Bougie verte

// Sell when:
// - RSI oversold + croisement de la MM
// - MACD en rouge + croisement
// - Bougie rouge

// Indicator settings
volMaLength = 65
stochLowerBand = 25

// Stochastic RSI settings
stochRsiLength = 10
stochLength = 10
stochRsi_kSmoothing = 5
stochRsi_dSmoothing = 5

// Stochastic settings
stoch_kLength = 8
stoch_kSmoothing = 5
stoch_dSmooting = 2

// Stochastic RSI calculation
smoothK = input.int(stochRsi_kSmoothing, minval=1)
smoothD = input.int(stochRsi_dSmoothing, minval=1)
lengthRSI = input.int(stochRsiLength, minval=1)
lengthStoch = input.int(stochLength, minval=1)
rsi = ta.rsi(close, lengthRSI)
stochRsi_k = ta.sma(ta.stoch(rsi, rsi, rsi, lengthStoch), smoothK)
stochRsi_d = ta.sma(stochRsi_k, smoothD)
buySignal_stochRsi = stochRsi_d < stochLowerBand

// Stochastic calculation
stoch_k = ta.sma(ta.stoch(close, high, low, stoch_kLength), stoch_kSmoothing)
stoch_d = ta.sma(stoch_k, stoch_dSmooting)
buySignal_stoch = ta.crossover(stoch_k, stoch_d) and stoch_k < stochLowerBand

// Volume condition
volMa = ta.sma(volume, volMaLength)
buySignal_volume = volume > volMa

// === Buy condition ===
// Buy when Stochastic RSI (D) crosses below lower band
buyCondition = buySignal_stochRsi and buySignal_stoch and buySignal_volume

// === Execute orders ===
if buyCondition
    strategy.entry("Buy", strategy.long)

// Plot buy and sell signals on the chart
plotshape(series=buyCondition, location=location.belowbar, color=color.green, style=shape.labelup, title="Buy Signal", text="BUY")
