//@version=5
strategy("Long Swing strategy (Weekly)", overlay=true, pyramiding=5, default_qty_type=strategy.percent_of_equity, default_qty_value=10)

// +++ Modify to buy:
// - Bougie verte

// Sell when:
// - Bougie rouge

// Indicator settings
volMaLength = 65

rsiLength = 14
rsiUpperBand = 60

macdFastLength = 12
macdSlowLength = 26
macdSignalLength = 9

stochLowerBand = 25

stochRsiLength = 10
stochLength = 10
stochRsi_kSmoothing = 5
stochRsi_dSmoothing = 5

stoch_kLength = 8
stoch_kSmoothing = 5
stoch_dSmooting = 2

// Stochastic RSI calculation
smoothK = input.int(stochRsi_kSmoothing, minval=1)
smoothD = input.int(stochRsi_dSmoothing, minval=1)
lengthRSI = input.int(stochRsiLength, minval=1)
lengthStoch = input.int(stochLength, minval=1)
rsi = ta.rsi(close, lengthRSI)
stochRsi_k = ta.sma(ta.stoch(rsi, rsi, rsi, lengthStoch), smoothK)
stochRsi_d = ta.sma(stochRsi_k, smoothD)
buySignal_stochRsi = stochRsi_d < stochLowerBand

// Stochastic calculation
stoch_k = ta.sma(ta.stoch(close, high, low, stoch_kLength), stoch_kSmoothing)
stoch_d = ta.sma(stoch_k, stoch_dSmooting)
buySignal_stoch = ta.crossover(stoch_k, stoch_d) and stoch_k < stochLowerBand

// Volume condition
volMa = ta.sma(volume, volMaLength)
buySignal_volume = volume > volMa

// RSI Calculation
rsi_value = ta.rsi(close, rsiLength)
rsi_sma = ta.sma(rsi_value, rsiLength)
upper_band = 60
sellSignal_rsi = rsi_value < rsi_sma and rsi_value > rsiUpperBand

// Calculate MACD Line and Signal Line using SMA
fast_ma = ta.sma(close, macdFastLength)
slow_ma = ta.sma(close, macdSlowLength)
macd = fast_ma - slow_ma
signal = ta.sma(macd, macdSignalLength)
histogram = macd - signal
sellSignal_macd = macd < signal and histogram < 0


// === Buy/Sell conditions ===
buyCondition = buySignal_stochRsi and buySignal_stoch and buySignal_volume
sellCondition = sellSignal_macd and sellSignal_rsi

// Determine if a position is still open
// Entering position signal activated only if not already in a trade
//isPositionOpen = strategy.position_size > 0
buySignal = buyCondition //and isPositionOpen == false
sellSignal = sellCondition //and isPositionOpen == true

var float thirdQuity = strategy.equity / 3    // Init buying order

// === Execute orders ===
if buySignal
    price = close
    maxShares = thirdQuity / price
    maxSharesRounded = math.floor(maxShares)
    strategy.entry("Buy", strategy.long, qty=maxSharesRounded)
if sellSignal
    strategy.close_all()
    thirdQuity := strategy.equity / 3

// Plot buy and sell signals on the chart
plotshape(series=buySignal, location=location.belowbar, color=color.green, style=shape.labelup, title="Buy Signal", text="BUY")
plotshape(series=sellSignal, location=location.abovebar, color=color.red, style=shape.labeldown, title="Sell Signal", text="SELL")
